compatibility_date = '2024-10-11'
compatibility_flags = [ 'nodejs_compat' ]
main = 'contact.js'
name = 'me2christ-worker'
route = 'worker.me2christ.com'
send_email = [{ name = 'SEND_EMAIL' }]

[observability]
enabled = true

[vars]
DISABLE_WORKER = false

# The rate limiting API is in open beta.
[[unsafe.bindings]]
name = 'RATE_LIMITER'
namespace_id = '1001' # An identifier you define, that is unique to your Cloudflare account. Must be an integer.
# limit: the number of tokens allowed within a given period in a single Cloudflare location
# period: the duration of the period, in seconds. Must be either 10 or 60
# NOTE: distibuted over many servers
simple = { limit = 1, period = 60 }
type = 'ratelimit'

[env.dev]
route = 'dev.worker.me2christ.com'
send_email = [{ name = 'SEND_EMAIL' }]

[env.dev.vars] # don't put email addresses here
DISABLE_WORKER = false
TURNSTILE_SECRET_KEY = '1x0000000000000000000000000000000AA'
