compatibility_date = '2024-10-11'
compatibility_flags = [ 'nodejs_compat' ]
main = 'contact.js'
name = 'me2christ-worker'
route = { pattern = 'worker.me2christ.com', custom_domain = true }

[observability]
enabled = true

[[send_email]]
name = 'SEND_EMAIL'

[vars]
DISABLE_WORKER = false

# The rate limiting API is in open beta.
[[unsafe.bindings]]
name = 'RATE_LIMITER'
namespace_id = '1001' # An identifier you define, that is unique to your Cloudflare account. Must be an integer.
# limit: the number of tokens allowed within a given period in a single Cloudflare location
# period: the duration of the period, in seconds. Must be either 10 or 60
# NOTE: distibuted over many servers
simple = { limit = 1, period = 60 }
type = 'ratelimit'

[env.dev]
custom_domain = true
route = 'dev.worker.me2christ.com'
vars = {
  EMAIL_FORWARD_ADDRESS = 'me2christ.andrew@gmail.com',
  EMAIL_WORKER_ADDRESS = 'andrew@me2christ.com',
  TURNSTILE_SECRET_KEY = '1x0000000000000000000000000000000AA'
}
