name = 'me2christ-worker'
main = 'contact.js'

compatibility_date = "2024-10-11"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true

[[send_email]]
name = "SEND_EMAIL"

[vars]
X = 'x'
Y = 'y'
